### ISSUE TITLE
How to get financials over past 4 years?

### ISSUE THREAD

**Issue by challengerlihan** [ranaroussi/yfinance#100]
This project is great, but I can only get financials for the last 4 years, like income/cash flow/balance sheet. Can you update the api to support all historical financials? Thanks!

**Comment by challengerlihan** [comment]
ok I checked your source code, since Yahoo has only got financials for the past 4 years so that's all you can get. Also, if I request the web pages too frequently it will get blocked right? So probably not a good way to download all historical data for all stocks...

**Comment by alvarob96** [comment]
Hi @challengerlihan!

I do not know if this can help you, but since Investing has a lot more data available than Yahoo, maybe you can use [investpy](https://github.com/alvarob96/investpy) if you want to retrieve historical data from stocks/equities from a time frame over 4 years.

Let me figure out if this solution helped you in any way! 💹

**Comment by ranaroussi** [comment]
The data isn't available on Yahoo! @alvarob96's solution might help.
