### ISSUE TITLE
TypeError: an integer is required (got type str) for endDt

### ISSUE THREAD

**Issue by matrak** [ranaroussi/yfinance#1030]
For the `Ticker#history` function in the fix introduced by commit: https://github.com/ranaroussi/yfinance/commit/9d5366d707d3f45ab84d3e92dc4edcb9498dcb7f
the `end` parameter has to be an integer, but the conversion to integer happens only under certain conditions:
`start or period is None or period.lower() == "max"`

In the current version (0.1.74) the call: `ticker.history(period='2y', interval='1d', end='2022-07-13')` would cause the following exception:
```
endDt = _pd.to_datetime(_datetime.datetime.fromtimestamp(end))
typeError: an integer is required (got type str)
```

**Comment by ValueRaider** [comment]
Setting aside the exception for now - how do you want the `end` argument to be used in this scenario? Currently it is ignored completely in Yahoo request, but you setting it implies you want it to be used. I ask because the correct fix might be to force user to leave start/end blank when setting period.

**Comment by matrak** [comment]
Sorry if this is an edge case, but from what I see (in the returned data) the `end` parameter is processed in the function call.

For the fix I would suggest to handle the `end` parameter independently from other input variables.
I would gladly provide a merge request with a fix by the end of the week.

**Comment by ValueRaider** [comment]
Correct that the `yfinance` function call uses `end` now, but this is a recent addition that post-processes the data after the Yahoo web request. For a long time before this commit, when `period` was set `yfinance` would completely ignore `end`.

This is a valid issue because `end` is ambiguous when `period` also set. I think it is nonsense to set both `period` and `start/end`.

**Comment by ValueRaider** [comment]
That PR is what I think is best solution. What do you think?
