### ISSUE TITLE
Whatever you did to timezone / cache recently broke my AWS Lambda function

### ISSUE THREAD

**Issue by ryanlampkin** [ranaroussi/yfinance#1107]
I never had this problem before this week. Seems like you've made changes to utils [image below]. With respect to AWS lambda, I am not able to "make directory / store".

![Untitled](https://user-images.githubusercontent.com/39038038/197408883-87ba8851-a931-42ab-a933-09f20488999a.png)

**Comment by ryanlampkin** [comment]
Last working version for me is 0.1.75

**Comment by ValueRaider** [comment]
Sorry about that. I've sent out a new release - 0.1.81

This was because I recently added a local caching store for timezone data, because accessing info[] first time is relatively expensive. It assumed access to default local cache folder.

I've also added function `set_tz_cache_location()`, in case there is somewhere you can write.

**Comment by ValueRaider** [comment]
This appears to be solved so will close.
