### ISSUE TITLE
Error with Latest yfianance 1.2.1

### ISSUE THREAD

**Issue by prolexgreen** [ranaroussi/yfinance#1261]
Traceback (most recent call last):
  File "C:\Users\coolb\anaconda3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\coolb\Downloads\Stock-Prediction-UI-master (1)\Stock-Prediction-UI-master\app.py", line 91, in run
    stock_data = data.DataReader(STOCK,
  File "C:\Users\coolb\anaconda3\lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\coolb\anaconda3\lib\site-packages\pandas_datareader\data.py", line 370, in DataReader
    return YahooDailyReader(
  File "C:\Users\coolb\anaconda3\lib\site-packages\pandas_datareader\base.py", line 253, in read
    df = self._read_one_data(self.url, params=self._get_params(self.symbols))
  File "C:\Users\coolb\anaconda3\lib\site-packages\pandas_datareader\yahoo\daily.py", line 153, in _read_one_data
    data = j["context"]["dispatcher"]["stores"]["HistoricalPriceStore"]
TypeError: string indices must be integers

**Comment by ValueRaider** [comment]
> Provide simple code that reproduces your problem

**Comment by noellwes** [comment]
I have been having this same issue since Friday, none of the patches seem to help. I think it relates to pandas data reader. 

My programs start with the following:

import pandas as pd
import numpy as np
import yfinance as yf
import datetime as dt
import pandas_datareader.data as web
from pandas_datareader import data as pdr

start = dt.datetime(2016, 1, 1)
end = dt.datetime.today()
df = web.DataReader('AAPL','yahoo', start, end)
stock= "AAPL"
fig = plt.figure('AAPL')
start = dt.datetime(2016, 1, 1)
end =  dt.date.today()
dividends = web.DataReader('AAPL', 'yahoo-dividends', start, end)
dividends.head()

**Comment by ValueRaider** [comment]
The bug is occurring where `pandas_datareader` tries to read 'root.App.main', which Yahoo encrypted recently. Problem is that package nothing to do with `yfinance`

**Comment by JoaoGoncalvesCS** [comment]
I appear to have the same issue, is there anyway we can overcome this issue? Any ideas ? Could we change the source maybe ?

**Comment by ValueRaider** [comment]
You got two options:
1 - Go to their GitHub project and ask them to fix. Nothing to do with this project
2 - Just use `yfinance`

**Comment by noellwes** [comment]
There is a comment in the linked thread about overide

https://github.com/pydata/pandas-datareader/issues/952

Yf.pdr_overide()

it fixed my programs. (Using updated yfinance ect)

Goodluck
