### ISSUE TITLE
Library using print rather than logger

### ISSUE THREAD

**Issue by dmoklaf** [ranaroussi/yfinance#1378]
The library is using print statements to warn the user, e.g.:

https://github.com/ranaroussi/yfinance/blob/ac6e047f0dc2e6ec446f95359bc55684f08370f4/yfinance/scrapers/quote.py#L129

This should be replaced by standard logs (logging.Logger) to allow the library client to process the logs correctly (e.g., redirect them to files, stdout, stderr, live notification streams, ...).

**Comment by asafravid** [comment]
@dmoklaf please fix an provide a pull request

**Comment by flaviovs** [comment]
@dmoklaf are you already working on a PR for this?

I totally agree that using loggers is more appropriate and pythonic for libraries. I'm willing to work on this, just checking to see if you have already started to avoid duplicate work.

**Comment by dmoklaf** [comment]
Hi, I can work on it in approx. 2 weeks, so no duplicate work until then. Let me know

**Comment by ValueRaider** [comment]
You 2 could work together btw. I can create a specific branch for you to merge into, for organisation. Not sure about granting direct write access, I need to get hold of Ran for that.

**Comment by flaviovs** [comment]
Hi @dmoklaf,
I've made the changes to my fork, will be testing them for a couple days after the current access situation is solved. The changes seem straightforward, so I expect to send the PR shortly thereafter.
Thank you

**Comment by dmoklaf** [comment]
That is great. Thank you!

**Comment by flaviovs** [comment]
Gents, here's the PR. Let me know if you need help with it.

**Comment by cmpunches** [comment]
This needs additional work.  Please see:

https://github.com/ranaroussi/yfinance/issues/1863

These should be throwing exceptions with the error messages (exceptions is the more common practice and is cleaner) instead of using stdout / stderr.  Logger is for applications if it's not going through a debug channel.  These prints and logger outputs also break ncurses ui's.  There's a whole plethora of reasons, but the big scary one is logic handling error conditions in returns.  This issue is highly visible in many downstream projects.

**Comment by flaviovs** [comment]
> These should be throwing exceptions with the error messages (exceptions is the more common practice and is cleaner) instead of using stdout / stderr.

100% agree -- library code should never print anything.

> Logger is for applications if it's not going through a debug channel.

No. Python's logging mechanism is a robust and elegant way to have logging in application **and libraries**. It is used across the board by Python's standard library modules and other modules in the python universe. A ncurses app that properly configures Python's logging (or don't configure it at all) should never be be affected by it. If it is, then the problem lies elsewhere.

Now, I agree that #1863 may be an issue though [@ValueRaider comment](https://github.com/ranaroussi/yfinance/issues/1863#issuecomment-1951203884) seems to address it.
