### ISSUE TITLE
Get stock symbol from stock name

### ISSUE THREAD

**Issue by navin772** [ranaroussi/yfinance#1384]
**Describe the problem**
A function that can return the stock symbol given the stock name.

**Describe the solution**
We can parse the HTML from the following link and can get the symbol from the first value in the list:
https://finance.yahoo.com/lookup?s={stock_name}
Example: https://finance.yahoo.com/lookup?s=apple (here we can return the symbol field of the first element)

**Additional context**
Sometimes user may want to search a particular stock but may not remember its stock symbol, so he/she can just pass the stock name.

**Comment by ValueRaider** [comment]
> return the first symbol

This is a problem because it presumes what the user wants = what Yahoo has put first. Maybe user wants a European listing. Or the most liquid listing which isn't always first e.g. https://finance.yahoo.com/lookup?s=i3+energy, the second match has most volume.

It also assume Yahoo search is good. E.g. https://finance.yahoo.com/lookup?s=appg the correct match is 18th.

So return all the results? How is this better than simply visiting the website?

**Comment by ValueRaider** [comment]
Is it really a problem?

**Comment by navin772** [comment]
No, it's not big of a problem. Just a feature I thought might help user interactivity in web apps (I was building one and felt the need). 
Anyway, I would close this issue.

**Comment by ValueRaider** [comment]
If you're experiencing it then is different, especially if you have users' experience to refine behaviour. You're free to implement in a fork, and if your users like then submit a Pull Request.
