### ISSUE TITLE
Issue when scraping option price real time

### ISSUE THREAD

**Issue by boukhicha** [ranaroussi/yfinance#1441]
I have written a small code to scrap data real time from Yahoo Finance HTML page, and it did work for a while until it got stuck and kept printing in the same value for 2 days. This code is used in bigger code to track stock price vs its expected move to get any overextended moves. I couldn't figure out how to solve this. Below is the code :

import requests
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt

symbol=('SPY')
url = f"https://finance.yahoo.com/quote/{symbol}"
page = requests.get(url)
soup = BeautifulSoup(page.text, "html.parser")
stock = soup.find(class_="Fw(b) Fz(36px) Mb(-4px) D(ib)")
print(stock.text)_

If anyone could help ! i would appreciate it

**Comment by ivan23kor** [comment]
Hi @boukhicha,
I ran your code and it's printing the correct (current) price from YahooFinance.

I'm guessing you are somehow looping this code and seeing the same old values printed, instead of real-time values. Could you attach your full code snippet here?

FIY, `yf.download('SPY', interval='1m')['Close'][-1]` will do what are trying to achieve.

**Comment by ivan23kor** [comment]
@boukhicha, sounds like you were testing while the US markets were closed over the weekend.

If you are getting proper values now, please close this issue.
