### ISSUE TITLE
yfinance info: can't find 'regularMarketPrice'

### ISSUE THREAD

**Issue by mritortousa** [ranaroussi/yfinance#1519]
I did update my yfinance and i cannot get any more stock quotes in last few days

did something happen

this is the version i am using 0.2.18 of yfinance

i am using  python 3.11

here are the errors

  File "C:\Users\mritorto\OneDrive - Deloitte (O365D)\Documents\python training\My test code\stock app\stockinput.py", line 13, in <module>
    print ("+ stock Current Market Price : ",GetstockInformation.info['regularMarketPrice'])
KeyError: 'regularMarketPrice'

I also was getting these errors also 

\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://query1.finance.yahoo.com/v7/finance/quote?formatted=true&lang=en-US&symbols=X

it looks like the keyword change to regularMarketPrice']) to current price 

why does it keep changing.  i notice a change a week or two ago also

it also has issues getting quotes on etf when it did not before

**Comment by rickturner2001** [comment]
@mritortousa can you give us more info about your code?  feel free to paste in the entire script

**Comment by mritortousa** [comment]
here is an example 

import yfinance as yahooFinance

GetmsftInformation = yahooFinance.Ticker("msft")


import yfinance as yahooFinance

voinfo = yahooFinance.Ticker("vo")

diainfo = yahooFinance.Ticker("dia")

qqqinfo = yahooFinance.Ticker("qqq")



##get previouse day price

print ("Microsoft Previous Day Market Price : ",GetmsftInformation.info['regularMarketPreviousClose'])


#get microsfot stock price

print ("Microsoft Current Market Price : ",GetmsftInformation.info['regularMarketPrice'])


##get previouse day price

print ("pseg Previous Day Market Price : ",peginfo .info['regularMarketPreviousClose'])

#get stock price

print ("pseg Current Market Price : ",peginfo.info['regularMarketPrice'])



##get previouse s& P index day price
#get s& pstock price

print ("S&P vo Previous Day Market Price : ",voinfo .info['regularMarketPreviousClose'])
print ("S&P vo  Current Market Price : ",voinfo.info['regularMarketPrice'])



##get previouse dow index day price

print ("dow  dia stock Previous Day Market Price : ",diainfo .info['regularMarketPreviousClose'])

#get dow stock price

print ("dow dia stock  Current Market Price : ",diainfo.info['regularMarketPrice'])

##get previouse dow index day price

print ("nsdaq qqq  Previous Day Market Price : ",diainfo .info['regularMarketPreviousClose'])

#get dow stock price

print ("nasday qqq  Current Market Price : ",diainfo.info['regularMarketPrice'])

**Comment by rickturner2001** [comment]
@mritortousa  Thank you for the code. I now understand what the problem is.

As you can see, when we run the code, we get a `KeyError` ( KeyError: 'regularMarketPrice')

A `KeyError` is raised by the Python interpreter when we try to access a non-existing key in a dictionary. In our case, the dictionary would be GetmsftInformation.info (by the way, you might want to take a quick look at PEP8 style guide: https://peps.python.org/pep-0008/)

This is the line in our code that raises the error:

```python
import yfinance as yf

msft = yf.Ticker("MSFT")

print("Microsoft Previous Day Market Price : ", msft.info['regularMarketPreviousClose'])


# This errors out because regularMarketPrice: KeyError: 'regularMarketPrice'
print("Microsoft Current Market Price : ", msft.info['regularMarketPrice'])
```

So `regularMarketPrice` does not exist in our dictionary, again, msft.info (I have taken the liberty to quickly refactor the code). The smart thing to do is to list all the keys that are available in the dictionary with the `.keys()` method. However, since there are many keys in msft.info, we can write a function to filter the keys based on a given keyword

```python
def search_key_by_keyword(data: dict, keyword: str) -> list[str]:
    return list(filter(lambda x: keyword in x.lower(), data.keys()))
```

We can now call this function with the correct parameters to get a list of valid keys that contain the word **market**

```python
valid_market_keys = search_key_by_keyword(msft.info, "market")
print(valid_market_keys)
```

**Output:**
` ['regularMarketPreviousClose', 'regularMarketOpen', 'regularMarketDayLow', 'regularMarketDayHigh', 'regularMarketVolume', 'marketCap']
`

**Comment by mritortousa** [comment]
i know that cause i did search and they change it from regular market to current price.

my question is why did that happen

i was looking to the the current stock price but having to keep changing the key word is a pain

question how to you print all the functions within a module to list line by line. I forgot how to do that with dir (module name)

**Comment by ValueRaider** [comment]
The `info dict` is fetched directly from Yahoo. If the keys have changed recently - within weeks not months - that's Yahoo.

**Comment by ValueRaider** [comment]
Continue discussion in #1518, it's basically the same problem.
