### ISSUE TITLE
Passing request session to yf.download

### ISSUE THREAD

**Issue by jkant** [ranaroussi/yfinance#1534]
Currently it is only possible to pass the request session to ticker objects. This means it is not possible for yf.download to use rate limiting and avoid pulling down corrupted data.

**Comment by bveber** [comment]
I added a PR that should fix this. 

I have it working locally, but I'm not seeing the expected behavior from the sample code with the custom `CachedLimiterSession`. I was expecting for a cache hit to bypass the rate-limiter, but in my testing I don't see any speedup for cache hits. I have verified the caching works without the rate-limiter (using only requests_cache.CacheMixin) but when I include the LimiterMixin from requests_ratelimiter my response time is always bottlenecked by the limiter. 

My problem is obviously external to this package but I'm curious if anyone has seen the same behavior.
