### ISSUE TITLE
yfinance 0.2.18 not importing financials (balance sheet, cashflows, P&L)

### ISSUE THREAD

**Issue by SebasHuayamares** [ranaroussi/yfinance#1540]
import yfinance as yf
aapl=yf.Ticker('AAPL')
aaple.get_balance_sheet

OUTPUT: <bound method TickerBase.get_balance_sheet of yfinance.Ticker object <AAPL>>
But no df with the actual statements

yfinance version 0.2.18 in Jupyter notebook from Anaconda running Python version 3.8.8 in a Macbook Pro

**Comment by paulmcq** [comment]
get_balance_sheet is a function, so parentheses are needed to call it:
`aapl.get_balance_sheet()`
Note also that `aaple` is misspelled in your example.

**Comment by ValueRaider** [comment]
Search through existing issues

**Comment by sumansuhag** [comment]
Hi!
Hey SebasHuayamares, it looks like you've bumped into a common little detail with Python syntax!

The message you're seeing, &lt;bound method TickerBase.get_balance_sheet of yfinance.Ticker object &gt;, is what happens when you mention a method without actually running it. You've pointed to the get_balance_sheet method, but you haven't told Python to do anything with it yet.

To get the DataFrame you want, just add some parentheses after the method name:

```python
import yfinance as yf
aapl = yf.Ticker('AAPL')
balance_sheet_df = aapl.get_balance_sheet() # Just add () here!
print(balance_sheet_df.head()) # This shows the first few rows of your DataFrame
```

A few tips for working with data retrieval methods like this:

1. Always Call: Don’t forget that you need those parentheses to run functions and methods in Python.
2. Assign to a Variable: It helps to store the result in a meaningful variable (like balance_sheet_df) for easier use later.
3. Check Your Data: After you call the method, use type(balance_sheet_df) to check if it’s a Pandas DataFrame. You can also use .head() or .info() to quickly look at what's inside.
4. Handle Errors: Keep in mind that get_balance_sheet() might return an empty DataFrame or None if there’s no data available for that ticker or date range, so it’s good to add some checks in your code.

yfinance is a handy library! Once you get the hang of this, check out other methods like aapl.info, aapl.history(), and aapl.dividends to grab even more financial info.
