### ISSUE TITLE
Only data until 2022-03-02 for 'dji' ticker

### ISSUE THREAD

**Issue by ZiyiXia** [ranaroussi/yfinance#1725]
### Describe bug

Can only get data before 2022-03-02 for 'dji' ticker.

### Simple code that reproduces your problem

`yf.download(tickers = "dji", start='2015-07-01', end='2023-07-01')`

### Debug log

N/A

### `yfinance` version

0.2.31

**Comment by lauchunhin** [comment]
@ZiyiXia 

In order to obtain Dow Jones Industrial Average data, the correct ticker symbol is `^DJI`, not `dji`. Yahoo Finance, however, offers data on DJI, a technology company headquartered in Shenzhen, as of *March 2, 2022*.  Instead of downloading data for this technology company, simply change the ticker symbol to `^DJI`.

Hopefully, this clears things up for you.
