### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED on stock.info and stock.financials

### ISSUE THREAD

**Issue by iatechicken** [ranaroussi/yfinance#393]
```
import yfinance as yf
msft = yf.Ticker("msft")
msft.info
msft.financials
```

so... most other functions are working... but `info` and `financials` are throwing ```SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)``` error. I got lazy and stopped testing others after financials, but pretty much went down the list from ```info``` on your README.md

I might have missed something but overall it's not a major issue since I just use ```yf.download``` to get most of the info that I need. Thanks for the great stuff!

**Comment by bala-v** [comment]
I got this error after fixing lxml dependency error (which was fixed by pip install lxml). The second error I got was "SSL:CERTIFICATE_VERIFY_FAILED". I was able to over this issue based on StackOverflow comments for Mac machine to install certficates in Python - 
![Screen Shot 2020-07-26 at 11 19 06 AM](https://user-images.githubusercontent.com/5421611/88486333-d7daa880-cf31-11ea-90cc-7733f45e44ca.png)

**Comment by iatechicken** [comment]
thank you!

**Comment by binfeng** [comment]
https://stackoverflow.com/a/42107877
