### ISSUE TITLE
Bug: wrong prices (.history)

### ISSUE THREAD

**Issue by muran123** [ranaroussi/yfinance#510]
Hi

I tried to load historic prices.
Based on 1x ticker example:

```
import yfinance as yf

ticker = 'AIR'
yf_ticker = yf.Ticker(ticker)
yf_historic_prices = yf_ticker.history(start="2015-12-01", end="2015-12-31")

```
Gives me the following result:
![grafik](https://user-images.githubusercontent.com/55026710/99906086-4871b600-2cd5-11eb-99b1-c3b939b4a869.png)

Based on yahoo finance: https://finance.yahoo.com/quote/AIR/history?period1=1448928000&period2=1451520000&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true
![grafik](https://user-images.githubusercontent.com/55026710/99906063-1bbd9e80-2cd5-11eb-850e-2e2dba3c2346.png)

-> different prices compared to the yahoo finance homepage (e.g. 30. December 2015 open=26.60 based on the homepage vs. open=25.54 based on the result of the code),  but the volume seems to be the same (e.g. 1. December 2015 same volume-> volume=118900 is correct) 

My guess is the code picks the wrong data, but displays the correct date. 
In base.py the start date and end date gets the correct timestamp. I could trace the url generated and used = 'https://query1.finance.yahoo.com/v8/finance/chart/AIR?period1=1448924400&period2=1451516400&interval=1d&includePrePost=False&events=div%2Csplits'

-> not sure, why it does not work. Does somebody have an idea why the generated url is not giving the correct prices?
Thank you

**Comment by Insoka** [comment]
Same for me for an other index the value was correct before (exactly the same command give the correct number) but not anymore (but in Yahoo the values are correct, it is possible it changes the number when it detects a software that taking the data but it is a strange method) and same happens here https://github.com/ranaroussi/yfinance/issues/626

It could be that Yahoo decides to not give us the correct results. I don't think it is a particular bug, but it could happens that a change in the libraries that Yfinance use bring some weird stuff. Have you the last version in every libraries ? Because I'm on the latest possible Python Libraries, because pandas seems to have change some stuffs. Anyway in my opinion it is more probable that Yahoo don't want us to use their data, in that case there will be no solution...

**Comment by ValueRaider** [comment]
You're comparing dividend-adjusted price against unadjusted.
