### ISSUE TITLE
Unable to get quarterly_financials

### ISSUE THREAD

**Issue by clairemalbrel** [ranaroussi/yfinance#533]
![Capture d’écran 2020-12-17 à 10 54 23](https://user-images.githubusercontent.com/64746471/102472177-55749180-4056-11eb-8536-c1e93cd536f8.png)

Hello ! 

I think there is a bug on msft.quarterly_financials /quaterly financials... anyone facing the same issue ? or am I doing something wrong ?

**Comment by binder2312** [comment]
I have the same issue

**Comment by TheEclipze** [comment]
Same issue here, this also applies to earnings, dividends, etc.

**Comment by simonvdv** [comment]
See the PR#534, URL has been fixed

**Comment by Chawforex** [comment]
Updated to 0.1.55 but this issue is still there.

**Comment by simonvdv** [comment]
You don't need to update, since it's still a pull request. Switch branch to the one with the changes in #534 (who is bachsh) : 
`git checkout bachsh`

Workaround if you've used `pip install yfinance` (strongly **not** advised though) is to manually include the changes in your local base.py (really poor practice, again, not advised;)

**Comment by fant59** [comment]
I'm update with `git clone` and `pip install` last versions.

And it doesn't work ☹️ 

Maybe YAHOO did any updates in there API ? 🤔

![image](https://user-images.githubusercontent.com/40704315/103243374-bb242000-496a-11eb-96b2-7dfba43b9d11.png)

**Comment by fant59** [comment]
> You don't need to update, since it's still a pull request. Switch branch to the one with the changes in #534 (which is from user bachsh) :
> `git checkout bachsh`
> 
> Workaround if you've used `pip install yfinance` (strongly **not** advised though) is to manually include the changes in your local base.py (really poor practice, again, not advised;)

Thx 😊👍👏 

It's worked! 😎

**Comment by simonvdv** [comment]
Maybe @ranaroussi might merge #534 (at least the base, not sure if the extra test modul is needed) ? Btw, let me know if you need/want a new contributor for the repo, I am always happy to help!

**Comment by SenorSultan** [comment]
> You don't need to update, since it's still a pull request. Switch branch to the one with the changes in #534 (which is from user bachsh) :
> `git checkout bachsh`
> 
> Workaround if you've used `pip install yfinance` (strongly **not** advised though) is to manually include the changes in your local base.py (really poor practice, again, not advised;)

Thanks! This worked for me as well. Can you explain why it is so ill advised?

**Comment by trueneu** [comment]
@SenorSultan - because you're manually messing with your package manager (pip, in this case). It's not meant to track local changes in files it assumes to be immutable. Since linking (not sure what's the correct term for Python) in Python is so easy, you're much better off downloading the source, using it in your application, and when the fix is included in upstream, ditch the fix and upgrade as usual.

**Comment by trueneu** [comment]
Also, maybe worth to mention: https://github.com/ranaroussi/yfinance/pull/480 has been merged, which handles the same problem, so no need to jump branches now. Just tried it, fixed the problem for me, although some people report it didn't help.
