### ISSUE TITLE
How pass the error YAHOO! FINANCE IS CURRENTLY DOWN! 

### ISSUE THREAD

**Issue by anotherJA** [ranaroussi/yfinance#537]
I'm scraping the data with yfinance.download for a long list of companies with a command :`for i in range(...): yfinance.download(table_symb[i],dstart,dend)` .
But sometimes I'm getting the error : "YAHOO! FINANCE IS CURRENTLY DOWN! "... and sometimes not (and for the same companies !).

I'd like to add to the program that when such an error occurs the program should try again to download the data until it works, or to stop with this download and continue the next company in my list. Like when the other error occurs : `No data found, symbol may be delisted`. In this latter case, the program doesn't stop, but gives up downloading it and goes on.

I assume this should be done in base.py in the line : `data = _requests.get(url=url, params=params, proxies=proxy)`, but I don't know how to proceed.

Do you have any idea please ?

**Comment by simonvdv** [comment]
This is not an yfinance issue per se.
You might wrap you yfinance call in a try...except block for instance. An since you get a 503 error probably due to being too fast between attempts, an idea would be to use a list of tickers that you modify only when data are retrieved (giving you the "pending" tickers at the end).

In pseudo-pseudocode :
tickers_lst =  [...]
while tickers_lst not empty:
  for tick in ticker_lst:
      try:
         download(tick)
         remove tick from ticker_lst
      except server down: continue

**Comment by ValueRaider** [comment]
Options:

- stop spamming
- [fetcher smarter](https://github.com/ranaroussi/yfinance#smarter-scraping)
- [yfinance_cache](https://github.com/ValueRaider/yfinance-cache)
