### ISSUE TITLE
Clarification on Ticker.financials

### ISSUE THREAD

**Issue by jkovach89** [ranaroussi/yfinance#582]
I'm getting odd numbers on the Ticker.financials function. For example:

`yf.Ticker("AAPL").quarterly_financials`

returns:

2020-12-26 | 2020-09-26
-- | -- | -- | --
Total Liab | 287830000000.000000 | 258549000000.000000
Total Stockholder Equity | 66224000000.000000 | 65339000000.000000
Other Current Liab | 55899000000.000000 | 47867000000.000000
Total Assets | 354054000000.000000 | 323888000000.000000
Common Stock | 51744000000.000000 | 50779000000.000000

Specifically, I'm looking for clarification on the "Common Stock" numbers. Looking at yahoo's data, I see 
![Screen Shot 2021-02-03 at 10 49 20 AM (2)](https://user-images.githubusercontent.com/31459861/106794456-b871b600-660d-11eb-96cc-d8b18950ac98.png)

which shows AAPL as having 16.79bn outstanding shares. However, common stock reported is 51.74bn. Am I misunderstanding this number? Or is the data incorrect?

**Comment by ericderace** [comment]
"Common Stock" is not the amount of outstanding shares. You can find the value for "Common Stock" in the Balance sheet tab (Quarterly), Total Equity Gross Minority Inte... > Stockholder' Equity > Common Stock.

**Comment by jkovach89** [comment]
@ericderace Thanks for the clarification. Is there anywhere in the API that pulls outstanding share data?

What does the common stock refer to?

Sorry, it's a great package but I'm still trying to figure out some of the data.

**Comment by ericderace** [comment]
@jkovach89 I'm actually not familiar with the API, I just tried the API for the first time and got to your issue by accident.

**Comment by jfgingras** [comment]
@jkovach89 If you look at Apple' Q4 2020 Financial Statements on the compagny [Investor Relations page](https://investor.apple.com/investor-relations/default.aspx#tabs_content--2020), you'll find the following under Shareholders’ equity :

> Common stock and additional paid-in capital, $0.00001 par value: 50,400,000 shares authorized; 16,976,763 and 17,772,945 shares issued and outstanding, respectively

_Note that the number of share are in thousands._

You can find out more about authorized, issued and outstanding shares [here](https://www.accountingcoach.com/stockholders-equity/explanation/2)

**Side notes**
The reason the par value is so low is common practice. First, corporations are required by law to assign a par value to issued shares. They typically choose the lowest possible value because the par value of a share of stock constitutes a binding two-way contract between the company and the shareholder.

If the compagny go bankrupt, its creditors can sue shareholders for the difference between the purchase price and the par value to recoup the unpaid debt. That way, your kinda protected.

Also, if the market price of the stock falls below the par value, the company may be liable to shareholders for the difference. So the compagny is protecting itself against you (the share holder).

**Comment by jemshit** [comment]
@jkovach89 outstanding shares is under the `info.sharesOutstanding`.
