### ISSUE TITLE
pdr_get_data doesn't stop after raised run time error

### ISSUE THREAD

**Issue by arielbell** [ranaroussi/yfinance#607]
Hi team,

I'm downloading a list of tickets.
In cases that one of the tickers fails to download, the pdr_get_data doesn't stop running and gets stuck.

The error: raise RuntimeError("*** YAHOO! FINANCE IS CURRENTLY DOWN! ***\n"
RuntimeError: *** YAHOO! FINANCE IS CURRENTLY DOWN! ***
Our engineers are working quickly to resolve the issue. Thank you for your patience.

Where it gets stuck: [*********************100%***********************]  51 of 55 completed (there were 4 failed).

Any commendation? I would be happy to continue with whichever tickers that were downloaded.  
I found this [thread](https://github.com/ranaroussi/yfinance/commit/6a8c637af758ff3de53f2ca3dafb6bf10f1902b9) but i'm not sure its related.

Thanks,
Ariel

**Comment by arielbell** [comment]
I believe it gets stuck here: 
while len(shared._DFS) < len(tickers):
            _time.sleep(0.01)

As we don't assign any ticker to the shared._DFS.
Just a  thought from a quick overview

**Comment by claudinho85** [comment]
I'm realizing the same error. 
How can we solve this problem?

Thanks
Claudio

**Comment by arielbell** [comment]
I tried this locally and it worked:
![image](https://user-images.githubusercontent.com/23659488/109061895-e7041d80-76ef-11eb-8e85-6ac67c5db661.png)

I took the error handling from the next section and added it here. 
it doesn't solve the issue of retrieving the data, but it helps the code finish its task as expected.

`if "Will be right back" in data.text:
            #data = data.json()
            err_msg = "No data found for this date range, symbol may be delisted"
            shared._DFS[self.ticker] = utils.empty_df()
            shared._ERRORS[self.ticker] = err_msg
            return shared._DFS[self.ticker]`

**Comment by claudinho85** [comment]
Thanks a lot for your response! :-)
However, what I've realized since yesterday is that I no longer retrieve historical data from just one request using yfinance.

Just to be more detailed, I used pdr.get_data_yahoo(tickers_list) with 5000 tickers in tickers_list and it worked till yesterday.
I dunno if Yahoo recognised this kind of behaviour and blocked it or it is weird that it doesn't work anymore.

How do you retrieve historical data for a huge group of tickers? I need to divide these requests with a time.sleep() between one and the other?

Thanks again

**Comment by claudinho85** [comment]
Ufortunately I found again error like **_"'Connection broken: IncompleteRead(3715 bytes read, 381 more expected)', IncompleteRead(3715 bytes read, 381 more expected))"_** but I dunno why

**Comment by ecourreges-orange** [comment]
I have the same issue of IncompleteRead once or twice a week and the program hangs on line 95 of multi.py which is the infinite loop with `_time.sleep(0.01)`

```
    # download using threads                                                                                                                                                                                 
    if threads:
	if threads is True:
            threads = min([len(tickers), _multitasking.cpu_count() * 2])
        _multitasking.set_max_threads(threads)
	for i, ticker in enumerate(tickers):
            _download_one_threaded(ticker, period=period, interval=interval,
                                   start=start, end=end, prepost=prepost,
                                   actions=actions, auto_adjust=auto_adjust,
                                   back_adjust=back_adjust,
                                   progress=(progress and i > 0), proxy=proxy,
                                   rounding=rounding)
        while len(shared._DFS) < len(tickers):
            _time.sleep(0.01)
```
I will try to post a PR for this today.
In the mean time, since I am only downloading one ticker, I'll just set `threads=False` to avoid the bug.
