### ISSUE TITLE
Data not pulling through for 11th March 2021?

### ISSUE THREAD

**Issue by ConfusedSpark** [ranaroussi/yfinance#624]
![image](https://user-images.githubusercontent.com/80512866/110964227-e2c03d00-834a-11eb-9566-07246e1a89eb.png)

pulling data for three tickers (pltr,crsr,amd) and it is not pulling anything for the 11th?

**Comment by mikekoba** [comment]
The row seems to be "gone" because of the below line.
https://github.com/ranaroussi/yfinance/blob/8bdc51f9fa71eae83c78cd04694eff60dfd6bb4d/yfinance/base.py#L220

It will drop any rows with missing data. If you navigate to https://finance.yahoo.com/quote/PLTR/history?p=PLTR under the "Historical Data" tab, most likely the row for March 11 was missing when you requested it (it is now populated).

I just noticed the same thing happening for BTC-USD. The JSON data provided from Yahoo! Finance shows "None" for that date, which is then dropped.
<img width="895" alt="Screen Shot 2021-03-14 at 5 48 11 PM" src="https://user-images.githubusercontent.com/23696969/111090589-7af62780-84ed-11eb-95cb-8ebf68dfe2a8.png">

**Comment by ConfusedSpark** [comment]
> ith missing d

Thanks for that!
When I was requesting data, it was fairly early in the trading session, so it may be that there is some timing issue (wouldnt think there would be, but who knows.).

Ill continue to monitor and see if this is a regular occurance.

**Comment by ConfusedSpark** [comment]
checked again today - seems yahoo do some odd updating... Not sure how to handle this tbh
![image](https://user-images.githubusercontent.com/80512866/111284616-2dd29c80-8638-11eb-8f25-11927c46fc0e.png)

**Comment by ConfusedSpark** [comment]
okay so this is completely on Yahoo finance.... they store the details of the previous day, when the market opens they wipe those details then repopulate at a later time. no idea why
