### ISSUE TITLE
TypeError: concat() got an unexpected keyword argument 'sort'

### ISSUE THREAD

**Issue by AashinShazar** [ranaroussi/yfinance#67]
![image](https://user-images.githubusercontent.com/44244230/58599720-52c50800-8236-11e9-86df-0024903eb86e.png)

What's going on here?

**Comment by ranaroussi** [comment]
Looks like you’re using an older version of pandas.

Run:

``pip install pandas -U``

And try again.  This error should be gone now.

Ran


On 30 May 2019, at 3:24, AashinShazar <notifications@github.com> wrote:

[image: image]
<https://user-images.githubusercontent.com/44244230/58599720-52c50800-8236-11e9-86df-0024903eb86e.png>

What's going on here?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ranaroussi/yfinance/issues/67?email_source=notifications&email_token=AAJBNMXCEBERI4XTIFFPFWTPX4NC7A5CNFSM4HQYZNIKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GWTTG3Q>,
or mute the thread

**Comment by ranaroussi** [comment]
Looks like you’re using an old version of pandas (yfinance requires Pandas >= 0.23.0).

Run "pip install pandas -U" and try again.  This error should be gone now.

Ran

**Comment by AashinShazar** [comment]
Ah that seemed like the issue. Thank you so much!

**Comment by ninjalu** [comment]
> Looks like you’re using an old version of pandas (yfinance requires Pandas >= 0.23.0).
> 
> Run "pip install pandas -U" and try again. This error should be gone now.
> 
> Ran

I have tried this but still not working :(. Any suggestions on why?
![Screen Shot 2019-11-13 at 21 41 09](https://user-images.githubusercontent.com/46543912/68806772-6b976d80-065e-11ea-8124-f0d1d95d05f2.png)

**Comment by ninjalu** [comment]
And even more strangely, it works perfectly on the tutorial I was trying to follow on my computer.
