### ISSUE TITLE
ChunkedEncodingError when reading data about ticker 

### ISSUE THREAD

**Issue by Mustufain** [ranaroussi/yfinance#675]
I am trying to read tickers info using the following code: 

`tickers_list = ['NIO',  'PLTR', 'MSFT']`

` tickers = '  '.join(tickers_list) `
  ` tickers = yf.Tickers(tickers)`
  ` print(tickers.tickers['NIO'].info)`
    
I get this error: 

requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(82 bytes read, 1069 more expected)', IncompleteRead(82 bytes read, 1069 more expected))

Environment: 
python 3.6.1 
MacOS BigSur

**Comment by HeadbangerFinance** [comment]
I'm getting the same when trying to download price history for stocks... 
I have been running these scripts several times daily for last years without much problem - but suddently they started to fail for well above 50% of the tickers I try to download since Thursday (1st of April). 
I'm running Python 3.8. 
I am experiencing these problems both in Windows and Linux environments... 
Would really appreciate if someone has any kind of input!

**Comment by dmitrievichh** [comment]
I also have this problem.

**Comment by HeadbangerFinance** [comment]
Have been trying various settings the last two days and I seem to get slightly more data with "threads"=False and I could probably live with the fact that you get some errors and that it is somewhat slow - but the primary problem right now is that the "ChunkedEncodingError" isn't returned until after almost 2 minutes...so it takes ages to run through a loop with try /except... Would be happy just to find a faster workaround at this stage, suggestions?

**Comment by walkeratwood** [comment]
I've also been getting this error a lot since April 1st. I'm running Python 3.8.7 on macOS Big Sur.

**Comment by HeadbangerFinance** [comment]
Thanks! Will try that workaround while yahoofinance behaves like it does currently!

**Comment by ValueRaider** [comment]
Latest version has timeout, can someone confirm problem gone.
