### ISSUE TITLE
Issue installing on Anaconda

### ISSUE THREAD

**Issue by srinathm535** [ranaroussi/yfinance#744]
Hi,

Trying to install this pkg on Anaconda. Getting below error. I already have pandas_datareader installed. Please help.

(base) C:\Windows\system32>conda install -c ranaroussi yfinance
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\ProgramData\Anaconda3

  added / updated specs:
    - yfinance

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    yfinance-0.1.54            |             py_0         735 KB  ranaroussi
    ------------------------------------------------------------
                                           Total:         735 KB

The following NEW packages will be INSTALLED:

  multitasking       ranaroussi/noarch::multitasking-0.0.9-py_0
  yfinance           ranaroussi/noarch::yfinance-0.1.54-py_0

The following packages will be UPDATED:

  conda              conda-forge::conda-4.10.1-py38haa244f~ --> pkgs/main::conda-4.10.1-py38haa95532_1

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi            conda-forge::certifi-2021.5.30-py38ha~ --> pkgs/main::certifi-2021.5.30-py38haa95532_0

Proceed ([y]/n)? y

Downloading and Extracting Packages
yfinance-0.1.54      | 735 KB    |                                                                              |   0%

InvalidArchiveError('Error with archive C:\\ProgramData\\Anaconda3\\pkgs\\yfinance-0.1.54-py_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\ncontains unsafe path: info/hash_input.json')

Appreciate your help in resolving this.

Thnaks!

**Comment by RobustCoder** [comment]
**It looks like you are a victim of a known BUG:** see [link1](https://github.com/ranaroussi/yfinance/issues/92) and [link2](https://github.com/conda/conda/issues/9913)

Work around is in link2 above, in aashishnk's 1st answer and then clarified by bakiba.

Here are the steps that I did months ago when I had this problem:
1. 	in Windows Explorer go to
 		C:\Users\DavidFrank\anaconda3\pkgs
2. 	create a new directory
 		yfinance-0.1.54-py_0
3. 	copy into that directory the file
 		C:\Users\DavidFrank\anaconda3\pkgs\yfinance-0.1.54-py_0.tar.bz2
4. 	right click on
 		C:\Users\DavidFrank\anaconda3\pkgs\yfinance-0.1.54-py_0\yfinance-0.1.54-py_0.tar.bz2
 and select 7-Zip --> Extract here
 That should extract the file
 		yfinance-0.1.54-py_0.tar
5. 	right click on
 		yfinance-0.1.54-py_0.tar
 and select 7-Zip --> Extract here
 That should extract the desired items.
6. 	delete the files
 		yfinance-0.1.54-py_0.tar.bz2
 		yfinance-0.1.54-py_0.tar
 inside
 		C:\Users\DavidFrank\anaconda3\pkgs\yfinance-0.1.54-py_0
7. 	rerun
 		`conda install -c ranaroussi yfinance`

_Unfortunately, while the steps above used to work for me, I cannot even get that InvalidArchiveError anymore._

Today I tried to add yfinance via Anaconda ([because I want the latest 0.1.63 version](https://github.com/ranaroussi/yfinance/issues/764)) by doing these steps:

1. Anaconda Navigator --> "Environments" tab --> click on the triangle beside the base (root) environment --> selecting "Open Terminal"
2. in that terminal, execute
		`conda install -c ranaroussi yfinance`

When I do that, I get a PackagesNotFoundError:

```
(base) C:\Users\brilly>conda install -c ranaroussi yfinance
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - yfinance

Current channels:

  - https://conda.anaconda.org/ranaroussi/win-64
  - https://conda.anaconda.org/ranaroussi/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Anyone know what is going on?**

_Is installation of yfinance using Anaconda hopeless?  Do I have to go outside Anaconda and use pip?_

**Comment by tuannguyen90** [comment]
I faced this issue, and resolved with this:

`conda install -c conda-forge yfinance`

reference: [https://anaconda.org/conda-forge/yfinance](url)
