### ISSUE TITLE
ticker.history('1d') give me 2 days

### ISSUE THREAD

**Issue by GF-Huang** [ranaroussi/yfinance#754]
![image](https://user-images.githubusercontent.com/4510984/124384781-7ad0a080-dd05-11eb-8297-92571c20eeb2.png)

**Comment by Gdango** [comment]
It looks like it's giving a two 1 day data (same date).   It only happens when you're asking for the most recent market closes date, but doesn't happen to the past data.

![image](https://user-images.githubusercontent.com/24763732/124704109-5f51cb00-dea8-11eb-87a2-d4b888a12ea6.png)

![image](https://user-images.githubusercontent.com/24763732/124704131-6d075080-dea8-11eb-87b9-62d1b802ecdd.png)
