### ISSUE TITLE
Importing Multiple Tickers - NaN Values

### ISSUE THREAD

**Issue by ghost** [ranaroussi/yfinance#799]
Hi,

If I import one ticker, I get no NaN values, but when importing multiple tickers together, it gives lots of NaN values in the dataset

**Comment by adam-s** [comment]
I'm having this problem today also.

**Comment by adam-s** [comment]
I'm having this problem today also. I changed the code to import tickers one at a time which is several times slower and it leaves the row blank instead of populating the value with NaN.

I created a colab notebook that recreates the error. https://colab.research.google.com/drive/1W_alDteC5qtdxSTtSpqRbOBm6qZMPUpI?usp=sharing

**Comment by atpnode** [comment]
I have switched to just importing one ticker at a time and now I am getting the NaN values again. I assume this is just yahoo lowering the rate limit even more?

**Comment by ValueRaider** [comment]
Options:

- stop spamming
- [fetcher smarter](https://github.com/ranaroussi/yfinance#smarter-scraping)
- [yfinance_cache](https://github.com/ValueRaider/yfinance-cache)
