### ISSUE TITLE
Support for quarterly financial data

### ISSUE THREAD

**Issue by martinbel** [ranaroussi/yfinance#90]
It would be great to be able to get the quarterly financial data together with the yearly data simply by adding more columns to the DataFrame.

**Comment by ps12345678** [comment]
How does one get the quarterly data, even if its separate data frame

**Comment by ps12345678** [comment]
> It would be great to be able to get the quarterly financial data together with the yearly data simply by adding more columns to the DataFrame.

How does one get Quarterly Financial. Even as a separate dataframe

**Comment by GregoryMorse** [comment]
Right now it uses pandas to get the only table there.  The quarterly simply uses JavaScript to pull out the data from a massive object on the web page.  Its pretty easy - need to find the <script> tag with this big object and make it JSON compatible which it probably already is then simply use JSON libs to parse it, and finally pull out the quarterly data.  Its not a large task, and a lot of other information is in the big JavaScript object as well including the normal info plus some more.

**Comment by nono-london** [comment]
HI,
which inspector do you use to isolate/find this <script> tag or the
relevant url access to the JSON libs?
At the moment i use Chrome, and can only find the related button but not
the associated JavaScript...
Thanks!

**Comment by GregoryMorse** [comment]
I simply as shown parsed the whole HTML blob as text for 'root.App.main = ' - then take the whole line and trim off that text and the semicolon.  It is a valid JSON string fortunately even though its technically JavaScript which sometimes has some subtle parsing differences with things like encoded characters e.g. single quotes.

Finding the script may be possible.  However you would probably need a very good HTML parser - and I found mostly in Python it was not possible using standard ones.  Mainly because modern websites design HTML for backwards compatibility and have non-perfect non-compliance issues throughout.  Hence the script tags are often not found as a starting point.  So just parsing the raw text blob is sufficient.  If you want to find it via script tags then certainly find a worthy HTML parser.

**Comment by nono-london** [comment]
Hi Gregory,
I have now located the blob on the source page. Nevertheless, although i
manage to access the source code with requests as text using python(which
does show the full information as you mentioned), when i try to parse it
with Beautifulsoup, the root.App.main blob get altered and relevant
information doesn't show anymore.
I used 'lxml' and 'html.parser' without any success.
How do you point your program to select the right bit of html?
Thanks a lot for the help

**Comment by GregoryMorse** [comment]
See #104 where the PR for this has the full code.

There is no HTML parsing.  Only text parsing, and JSON parsing.  So BeautifulSoup, etc do not come into play at all.  The full code is there, tested and working, hopefully in a soon new release.
