### ISSUE TITLE
ADJ Close and Close converge at the end of the download.

### ISSUE THREAD

**Issue by Originn** [ranaroussi/yfinance#985]
When downloading a stock price using 
`df = yf.download(selected, start=request.form.get("start"), end=request.form.get("end"), auto_adjust = False, prepost = False, threads = True, proxy = None)[["Adj Close", "Close"]].dropna(axis=1, how='all')`

where Start date is 01-01-2015 and End date is 01-01-2020 the resulting ADJ close price and Close price are different all across the date range but converge at the last 100 rows. Am I missing something here ot there is an issue?

I used the ticker OCFC in my last examination, but it seems to presist across all tickers.

**Comment by bkestelman** [comment]
Adjusted price is a _historical_ adjustment to account for stock splits. The current adjusted price of a stock is always the same as the current raw price because there's nothing to adjust. If you look back in time, say 1 year ago, and there was a split in that time, then the historic prices before the split need to be adjusted.
