### ISSUE TITLE
Memory leak when using Threads

### ISSUE THREAD

**Issue by sityware** [ranaroussi/yfinance#992]
When using Threads on a yfinance download, after each request this adds to the processes memory usage and does not get released.

To replicate, create a new python file with the below simple code to download two symbols using threads. 
Run this in a Linux environment, as this is needed to easily show the memory usage. Also verified using Top command.

When you remove the Threads option, the memory no longer leaks.

    import resource
    import yfinance as yf
    import time
    
    while True:
        data_prevClose = yf.download(tickers="AAPL,TSLA", period="1d", interval="1d", group_by='column', auto_adjust=True, prepost=True, threads=True, proxy=None)
        print ('Memory usage: %s (kb)' % resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)
        time.sleep(5)

Example

    [*********************100%***********************]  2 of 2 completed
    Memory usage: 50968 (kb)
    [*********************100%***********************]  2 of 2 completed
    Memory usage: 51048 (kb)
    [*********************100%***********************]  2 of 2 completed
    Memory usage: 51068 (kb)
    [*********************100%***********************]  2 of 2 completed
    Memory usage: 51068 (kb)
    [*********************100%***********************]  2 of 2 completed
    Memory usage: 51084 (kb)
    [*********************100%***********************]  2 of 2 completed
    Memory usage: 51096 (kb)

I know it is not normal to request every five seconds, but over time on a long running uptime, it could get concerning.
Tested on latest 0.1.70

**Comment by devfinwiz** [comment]
I would recommend using Thread Pool Executors instead of simply passing threads=True as one of the parameters to the download method. I know Thread Pool Executors are od fashioned but they'll most probably solve your problem. 

https://www.pythontutorial.net/advanced-python/python-threadpoolexecutor/

Refer the above URL if you're not aware how Thread Pool Executors function. 
Here's a code snippet too for you to understand how you must proceed:

import concurrent.futures
with concurrent.futures.ThreadPoolExecutor() as executor:
 
    tickers=tickers_list[700:1243] 
    results=executor.map(book_value_computer,tickers)

Here book_value_computer is the name of the method where the implementation is available and tickers is the iterator. 

You may also refer my repository for stuff related to Yfinance and Stocks: https://github.com/devfinwiz/Stock_Screeners

**Comment by ValueRaider** [comment]
This appears fixed. I can reproduce in old versions, but not latest.
